/**
 * Affinity tables for Event Fit Score calculation.
 * Maps event categories to user interests and goals with weighted affinity values (0–1).
 */

export const CATEGORY_INTEREST_AFFINITY: Record<string, Record<string, number>> = {
  "Trekking & Outdoor": {
    "Trekking e camminate": 1.0,
    "Esperienze outdoor particolari": 0.9,
    "Avventura e sfida": 0.8,
    "Scoprire posti nuovi": 0.7,
    "Fare movimento": 0.6,
    "Relax": 0.4,
    "Conoscere persone": 0.3,
    "Eventi social": 0.3,
    "Cene e momenti conviviali": 0.2,
    "Aperitivi e tramonti": 0.2,
    "Eventi serali": 0.1,
  },
  "Sport & Movimento": {
    "Fare movimento": 1.0,
    "Avventura e sfida": 0.8,
    "Trekking e camminate": 0.7,
    "Esperienze outdoor particolari": 0.6,
    "Conoscere persone": 0.4,
    "Eventi social": 0.4,
    "Relax": 0.3,
    "Scoprire posti nuovi": 0.3,
    "Cene e momenti conviviali": 0.2,
    "Aperitivi e tramonti": 0.1,
    "Eventi serali": 0.1,
  },
  "Social & Aperitivi": {
    "Conoscere persone": 1.0,
    "Cene e momenti conviviali": 1.0,
    "Aperitivi e tramonti": 1.0,
    "Eventi social": 1.0,
    "Relax": 0.8,
    "Scoprire posti nuovi": 0.5,
    "Fare movimento": 0.2,
    "Trekking e camminate": 0.1,
    "Esperienze outdoor particolari": 0.1,
    "Avventura e sfida": 0.1,
    "Eventi serali": 0.7,
  },
  "Esperienze & Cultura": {
    "Scoprire posti nuovi": 1.0,
    "Relax": 0.7,
    "Conoscere persone": 0.6,
    "Eventi social": 0.5,
    "Cene e momenti conviviali": 0.4,
    "Aperitivi e tramonti": 0.4,
    "Esperienze outdoor particolari": 0.4,
    "Trekking e camminate": 0.2,
    "Fare movimento": 0.2,
    "Avventura e sfida": 0.2,
    "Eventi serali": 0.3,
  },
  "Eventi Speciali": {
    "Esperienze outdoor particolari": 1.0,
    "Avventura e sfida": 0.9,
    "Scoprire posti nuovi": 0.8,
    "Conoscere persone": 0.6,
    "Relax": 0.5,
    "Cene e momenti conviviali": 0.5,
    "Eventi social": 0.5,
    "Aperitivi e tramonti": 0.4,
    "Fare movimento": 0.4,
    "Trekking e camminate": 0.4,
    "Eventi serali": 0.3,
  },
};

export const CATEGORY_GOAL_AFFINITY: Record<string, Record<string, number>> = {
  "Trekking & Outdoor": {
    "Relax": 0.5,
    "Conoscere persone": 0.4,
    "Fare movimento": 0.8,
    "Scoprire posti nuovi": 0.9,
    "Mettermi alla prova": 1.0,
  },
  "Sport & Movimento": {
    "Relax": 0.2,
    "Conoscere persone": 0.4,
    "Fare movimento": 1.0,
    "Scoprire posti nuovi": 0.4,
    "Mettermi alla prova": 0.9,
  },
  "Social & Aperitivi": {
    "Relax": 0.9,
    "Conoscere persone": 1.0,
    "Fare movimento": 0.1,
    "Scoprire posti nuovi": 0.5,
    "Mettermi alla prova": 0.1,
  },
  "Esperienze & Cultura": {
    "Relax": 0.7,
    "Conoscere persone": 0.5,
    "Fare movimento": 0.2,
    "Scoprire posti nuovi": 1.0,
    "Mettermi alla prova": 0.3,
  },
  "Eventi Speciali": {
    "Relax": 0.5,
    "Conoscere persone": 0.6,
    "Fare movimento": 0.4,
    "Scoprire posti nuovi": 0.8,
    "Mettermi alla prova": 0.9,
  },
};
