project_id = "istotjnoqtrtthnyreyv"

[functions.create-event-checkout]
verify_jwt = false

[functions.create-membership-checkout]
verify_jwt = false

[functions.verify-event-payment]
verify_jwt = true

[functions.verify-membership-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.process-refund]
verify_jwt = true

[functions.notify-event-cancelled]
verify_jwt = true

[functions.change-registration-price-option]
verify_jwt = true
