import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "it" | "en";

type TranslationKeys = typeof translations.it;

const translations = {
  it: {
    // Navigation
    home: "Home",
    myEvents: "I Miei Eventi",
    organize: "Organizza",
    merch: "Merch",
    profile: "Profilo",

    // Header
    search: "Cerca",
    toggleTheme: "Cambia tema",
    signIn: "Accedi",

    // Index / Home
    searchEvents: "Cerca eventi...",
    date: "Data",
    allPrices: "Tutti i prezzi",
    free: "Gratuito",
    paid: "A pagamento",
    clearAll: "Cancella tutto",
    searchResults: "Risultati ricerca",
    upcomingEvents: "Prossimi Eventi",
    noEventsFound: "Nessun evento trovato",
    clearFilters: "Cancella filtri",
    featuredEvent: "Evento in Evidenza",
    discover: "Scopri",
    today: "Oggi!",
    tomorrow: "Domani",
    past: "Passato",
    inDays: "Tra {days} giorni",
    spotsLeft: "{count} posti rimasti",

    // Event Card
    draft: "Bozza",
    open: "Aperto",
    full: "Pieno",
    closed: "Chiuso",
    cancelled: "Cancellato",

    // Event Detail
    description: "Descrizione",
    gallery: "Galleria",
    equipment: "Attrezzatura",
    mandatoryEquipment: "Attrezzatura Obbligatoria",
    recommendedEquipment: "Attrezzatura Consigliata",
    safetyNotice: "Avviso di sicurezza:",
    safetyNoticeText: "I partecipanti che si presentano senza l'attrezzatura obbligatoria richiesta potrebbero non essere ammessi all'attività per motivi di sicurezza.",
    meetingPoints: "Punti di Ritrovo",
    participants: "Partecipanti",
    joined: "Iscritti",
    noParticipantsYet: "Ancora nessun partecipante",
    signInAndJoin: "Accedi e iscriviti per vedere chi partecipa.",
    joinToSee: "Iscriviti per vedere chi partecipa.",
    beFirstToJoin: "Sii il primo a iscriverti.",
    signInAndBe: "Accedi e sii il primo a iscriverti.",
    organizer: "Organizzatore",
    viewProfile: "Vedi Profilo",
    contactInfoNotAvailable: "Informazioni di contatto non disponibili",
    signInToContact: "Accedi per contattare l'organizzatore",
    directions: "Indicazioni",
    addToCalendar: "Aggiungi al Calendario",
    distance: "Distanza",
    elevation: "Dislivello",
    duration: "Durata",
    spots: "Posti",
    price: "Prezzo",
    from: "Da",
    yourPrice: "Il tuo prezzo",
    deposit: "Acconto",
    total: "totale",
    payOnLocation: "paga in loco",
    eventClosed: "Evento Chiuso",
    signInToJoin: "Accedi per Iscriverti",
    approvalPending: "In Attesa di Approvazione",
    onWaitlist: "In Lista d'Attesa",
    payNow: "Paga Ora",
    registered: "Iscritto ✔",
    joinWaitlist: "Iscriviti alla Lista d'Attesa",
    viewRequirements: "Vedi Requisiti",
    joinEvent: "Iscriviti",
    requestManualApproval: "Richiedi approvazione manuale",
    cancelRegistration: "Cancella Iscrizione",
    cancelling: "Cancellazione...",

    // Registration Dialog
    registerFor: "Registrati per {title}",
    completeRegistration: "Completa la registrazione selezionando le opzioni richieste.",
    meetingPoint: "Punto di Ritrovo",
    sportLevel: "Livello Sportivo",
    beginner: "Principiante",
    intermediate: "Intermedio",
    advanced: "Avanzato",
    orEnterCustomLevel: "Oppure inserisci il livello personalizzato (es. 3.5 per padel)",
    helpsOrganizers: "Aiuta gli organizzatori a bilanciare le squadre e pianificare le attività",
    choosePricingOption: "Scegli l'opzione di prezzo",
    discountCode: "Codice Sconto",
    optional: "opzionale",
    membershipRequired: "Tessera Associativa Richiesta",
    membershipRenewalRequired: "Rinnovo Tessera Richiesto",
    orderSummary: "Riepilogo Ordine",
    event: "Evento",
    discountApplied: "Sconto applicato",
    remainingPayLater: "Rimanente (paga dopo)",
    paymentOnLocation: "Pagamento in loco — nessun addebito durante la registrazione.",
    membershipFee: "Quota associativa",
    totalDueToday: "Totale dovuto oggi",
    membershipIncludedInCheckout: "La quota associativa è inclusa in questo checkout Stripe.",
    fullPaymentViaStripe: "L'intero importo verrà addebitato online tramite Stripe.",
    depositViaStripe: "L'acconto verrà addebitato online tramite Stripe.",
    confirmRegistration: "Conferma Iscrizione",
    renewMembershipAndRegister: "Rinnova Tessera e Iscriviti",
    payMembershipAndRegister: "Paga Tessera e Iscriviti",
    submitRequest: "Invia Richiesta",
    redirectingToPayment: "Reindirizzamento al pagamento...",
    registering: "Registrazione...",
    submitting: "Invio...",
    equipmentConfirmation: "Ho l'attrezzatura obbligatoria richiesta",

    // Membership Info
    membershipCardTitle: "Tessera Associativa Scampagnate",
    membershipExpiredText: "La tua tessera associativa è scaduta. Per continuare a partecipare alle attività è necessario rinnovare la tessera.",
    membershipKeepId: "Il tuo numero di tessera verrà mantenuto.",
    membershipNewText: "Per partecipare alle attività organizzate dal Gruppo Scampagnate, è richiesta la tessera associativa annuale.",
    membershipAfterPayment: "Dopo il pagamento riceverai il tuo numero di tessera personale. La tessera fisica verrà consegnata durante il tuo primo evento.",
    membershipFeePerYear: "La quota associativa è di €10/anno e copre l'intero anno solare {year}.",

    // Payment Info
    fullPaymentOnline: "Pagamento Completo Online",
    paymentOnLocationTitle: "Pagamento in Loco",
    splitPayment: "Pagamento Rateale",
    totalPrice: "Prezzo totale",
    depositOnlineStripe: "Acconto (online via Stripe)",
    remainingBalance: "Saldo rimanente",
    remainingBalanceText: "Il saldo rimanente può essere pagato prima dell'evento o in loco.",
    fullAmountStripe: "L'intero importo verrà addebitato online tramite Stripe durante la registrazione.",
    paymentCollectedOnLocation: "Il pagamento verrà effettuato in loco all'evento.",
    depositRefundPolicy: "Il rimborso dell'acconto è soggetto a questa policy.",
    cancellationPolicy: "Policy di Cancellazione",

    // Access Warning
    accessRequirements: "Requisiti di accesso",
    requirementsNotMet: "Requisiti non soddisfatti:",
    accessWarningDefault: "Questo evento ha dei requisiti di partecipazione.",
    accessWarningText: "Puoi comunque richiedere l'approvazione manuale dell'organizzatore oppure contattarlo direttamente per maggiori informazioni.",
    contactOrganizer: "Contatta l'organizzatore",
    requestManualApprovalBtn: "Richiedi approvazione manuale",
    close: "Chiudi",

    // Private/Hidden
    private: "Privato",
    hidden: "Nascosto",

    // My Events
    upcoming: "Prossimi",
    saved: "Salvati",
    noUpcomingEvents: "Nessun evento prossimo.",
    browseEvents: "Esplora Eventi",
    noSavedEvents: "Nessun evento salvato.",
    tapBookmark: "Tocca l'icona segnalibro su qualsiasi evento per salvarlo.",
    noPastEvents: "Nessun evento passato.",
    share: "Condividi",
    calendar: "Calendario",
    cancel: "Cancella",
    cancelRegistrationTitle: "Cancellare l'Iscrizione?",
    cancelRegistrationText: "Sei sicuro di voler cancellare la tua iscrizione per {title}?",
    keep: "Mantieni",

    // Profile
    signInToViewProfile: "Accedi per vedere il tuo profilo.",
    firstName: "Nome",
    lastName: "Cognome",
    phone: "Telefono",
    bio: "Bio",
    categoryPreferences: "Preferenze Categorie",
    preferences: "Preferenze",
    membership: "Tessera",
    status: "Stato",
    activeMember: "Membro Attivo",
    expiredMember: "Scaduto",
    inactiveMember: "Membro Inattivo",
    foundingMember: "Founding Member",
    memberId: "Numero Tessera",
    memberSince: "Membro Dal",
    validUntil: "Valido Fino Al",
    membershipExpiredRenew: "La tua tessera è scaduta. Rinnova per continuare a partecipare agli eventi.",
    joinFirstEvent: "Iscriviti al tuo primo evento per attivare la tessera annuale e ricevere il tuo numero personale!",
    badges: "Badge",
    officialMember: "Membro ufficiale della community",
    nextBadge: "Prossimo badge",
    joinEventsToEarnBadges: "Partecipa agli eventi per guadagnare badge!",
    pastEvents: "Eventi Passati",
    noPastEventsJoinFirst: "Nessun evento passato. Partecipa al tuo primo evento!",
    helpAndInfo: "Aiuto e Informazioni",
    trekkingDifficultyGuide: "Guida Difficoltà Trekking",
    signOut: "Esci",
    profileUpdated: "Profilo aggiornato!",
    profilePhotoUpdated: "Foto profilo aggiornata!",
    points: "punti",
    copied: "Copiato!",
    memberIdCopied: "Numero Tessera #{id} copiato.",

    // Auth
    welcomeBack: "Bentornato!",
    joinUs: "Unisciti a Noi",
    signInToAccount: "Accedi al tuo account",
    createAccount: "Crea il tuo account Scampagnate",
    continueWithGoogle: "Continua con Google",
    continueWithApple: "Continua con Apple",
    orContinueWithEmail: "Oppure continua con email",
    email: "Email",
    password: "Password",
    rememberMe: "Ricordami",
    forgotPassword: "Password dimenticata?",
    signingIn: "Accesso...",
    signingUp: "Registrazione...",
    signUp: "Registrati",
    dontHaveAccount: "Non hai un account?",
    alreadyHaveAccount: "Hai già un account?",
    acceptPrivacy: "Accetto la",
    privacyPolicy: "Privacy Policy",
    and: "e i",
    termsOfService: "Termini di Servizio",
    viewDifficultyGuide: "Vedi Guida Difficoltà Trekking",
    learnCriteria: "Scopri i nostri 5 livelli standardizzati per partecipare agli eventi in sicurezza.",
    resetPassword: "Reset Password",
    resetPasswordDesc: "Inserisci la tua email e ti invieremo un link di reset",
    sendResetLink: "Invia Link di Reset",
    sending: "Invio...",
    backToSignIn: "Torna al Login",
    passwordStrengthWeak: "Debole",
    passwordStrengthFair: "Discreto",
    passwordStrengthGood: "Buono",
    passwordStrengthStrong: "Forte",
    atLeast8Chars: "Almeno 8 caratteri",
    uppercaseLetter: "Lettera maiuscola",
    lowercaseLetter: "Lettera minuscola",
    number: "Numero",
    specialCharacter: "Carattere speciale",
    accountCreated: "Benvenuto! Il tuo account è stato creato.",
    registrationComplete: "Registrazione completata! Controlla la tua email per confermare il tuo account.",
    errorAcceptPrivacy: "Devi accettare la privacy policy",
    emailSent: "Email inviata!",
    checkEmailReset: "Controlla la tua email per resettare la password.",
    enterYourEmail: "Inserisci la tua email",
    pleaseEnterEmail: "Per favore inserisci il tuo indirizzo email.",

    // Merch
    merchandise: "Merchandise",
    merchDescription: "Prodotti ufficiali Scampagnate. Contattaci via WhatsApp per acquistare.",
    whatsapp: "WhatsApp",
    merchOrderInfo: "Tutti gli ordini sono gestiti manualmente via WhatsApp.",
    merchDeliveryInfo: "I dettagli di consegna e pagamento saranno concordati direttamente con il team.",

    // Notifications
    notifications: "Notifiche",
    markAll: "Segna tutte",
    noNotifications: "Nessuna notifica",
    notificationsWillAppear: "Le notifiche appariranno qui",
    pushOn: "Push ON",
    push: "Push",
    openNavigation: "Apri Navigazione",

    // Not Found
    pageNotFound: "Oops! Pagina non trovata",
    returnToHome: "Torna alla Home",

    // Proposal
    proposeActivity: "Proponi Attività",
    haveIdea: "Hai un'idea per una nuova attività?",
    proposeIt: "Proponila alla community!",
    thankYouProposal: "Grazie per la tua proposta!",
    proposalReview: "Il team di Scampagnate la valuterà e potrebbe contattarti per organizzare l'attività.",
    proposeActivityTitle: "Proponi un'Attività",
    proposeActivityDesc: "Suggerisci una nuova attività alla community. Il team valuterà la tua proposta.",
    yourName: "Il tuo nome",
    activityTitle: "Titolo attività",
    whatIsIt: "Di cosa si tratta?",
    location: "Luogo",
    locationPlaceholder: "Città, luogo specifico o link Google Maps",
    suggestedDate: "Data suggerita",
    time: "Orario",
    maxParticipants: "Numero massimo partecipanti",
    submitProposal: "Invia Proposta",

    // Report Issue
    reportIssue: "Segnala un Problema",
    title: "Titolo",
    briefSummary: "Breve riepilogo del problema",
    descriptionLabel: "Descrizione",
    describeIssue: "Descrivi il problema in dettaglio...",
    priority: "Priorità",
    low: "Bassa",
    medium: "Media",
    high: "Alta",
    submitReport: "Invia Segnalazione",
    thankYouReporting: "Grazie per la segnalazione!",
    reportReceived: "Abbiamo ricevuto la tua segnalazione e la esamineremo al più presto.",
    pleaseFillFields: "Per favore compila tutti i campi",
    inputTooLong: "Testo troppo lungo",
    titleMax200: "Titolo max 200 caratteri, descrizione max 2000 caratteri.",

    // Toasts & messages
    error: "Errore",
    requestSent: "Richiesta inviata",
    manualApprovalSent: "La tua richiesta di approvazione manuale è stata inviata all'organizzatore.",
    addedToWaitlist: "Aggiunto alla lista d'attesa",
    waitlistNotify: "Sarai avvisato quando si libererà un posto per {title}",
    registrationConfirmed: "Iscrizione confermata",
    registeredFor: "Ti sei iscritto a {title}",
    registrationCancelled: "Iscrizione cancellata",
    registrationCancelledDesc: "La tua iscrizione è stata cancellata.",
    removedFromSaved: "Rimosso dai salvati",
    savedToWishlist: "Salvato nella wishlist",
    removedFromSavedEvents: "Rimosso dagli eventi salvati",
    paymentCompleted: "Pagamento completato",
    discountCoveredAmount: "Lo sconto ha coperto l'intero importo!",
    uploadError: "Errore di caricamento",

    statusPaid: "Pagato",
    attended: "Partecipato",
    noShow: "Non presentato",

    // Payment/Membership Success
    verifyingPayment: "Verifica pagamento...",
    verifyingPaymentDesc: "Stiamo verificando il tuo pagamento.",
    paymentConfirmedTitle: "Pagamento Confermato! 🎉",
    paymentConfirmedDesc: "Il pagamento è stato registrato. Sei ufficialmente iscritto all'evento!",
    backToEvent: "Torna all'evento",
    goToHome: "Vai alla Home",
    verificationError: "Errore di Verifica",
    verificationErrorDesc: "Non siamo riusciti a verificare il pagamento. Se hai già pagato, contatta il supporto.",
    paymentConfirmedToast: "Pagamento confermato!",
    paymentConfirmedToastDesc: "Il tuo pagamento è stato registrato con successo.",
    membershipActivatedTitle: "Tessera Attivata! 🎉",
    membershipActivatedDesc: "La tua tessera associativa Scampagnate è ora attiva. Puoi partecipare a tutti gli eventi!",
    membershipActivatedToast: "Tessera attivata!",
    membershipActivatedToastDesc: "La tua tessera associativa è ora attiva.",
    verifyingMembership: "Verifica in corso...",
    verifyingMembershipDesc: "Stiamo verificando il tuo pagamento e attivando la tessera.",

    // Profile Setup
    completeYourProfile: "Completa il tuo Profilo",
    fewMoreDetails: "Solo pochi dettagli prima di poter partecipare agli eventi.",
    uploadProfilePhoto: "Carica una foto profilo (opzionale)",
    phoneNumber: "Numero di Telefono *",
    phoneDisclaimer: "Il tuo numero di telefono verrà utilizzato esclusivamente per scopi legati agli eventi, come coordinamento, aggiornamenti dell'ultimo minuto o comunicazioni di emergenza da parte degli organizzatori. Questa informazione non sarà visibile pubblicamente agli altri partecipanti.",
    experienceAndActivity: "Esperienza e Attività",
    experienceExplanation: "Per aiutarci a consigliare eventi adatti alla tua esperienza e garantire la sicurezza di tutti durante le attività all'aperto, ti chiediamo un paio di domande rapide sulla tua esperienza di trekking e le tue abitudini di attività fisica. Le tue risposte aiutano gli organizzatori a pianificare le attività in modo responsabile.",
    trekkingQuestion: "Quante esperienze di trekking o escursioni hai completato finora?",
    activityQuestion: "Con che frequenza pratichi attività fisica?",
    moreThan2Week: "Più di 2 volte a settimana",
    oneToTwoWeek: "1–2 volte a settimana",
    rarely: "Raramente",
    saving: "Salvataggio...",
    completeSetup: "Completa Setup",
    photoUpdated: "Foto aggiornata!",
    phoneRequired: "Numero di telefono richiesto",
    answerAllQuestions: "Per favore rispondi a tutte le domande",
    profileSetupComplete: "Setup profilo completato!",
    welcomeToScampagnate: "Benvenuto in Scampagnate.",

    // Reset Password
    newPassword: "Nuova Password",
    newPasswordLabel: "Nuova password",
    confirmPasswordLabel: "Conferma password",
    updatePassword: "Aggiorna Password",
    updating: "Aggiornamento...",
    passwordUpdated: "Password aggiornata!",
    passwordsNoMatch: "Le password non corrispondono.",
    invalidLink: "Link non valido.",
    backToLogin: "Torna al Login",

    // Misc
    everyoneJoining: "Tutti i partecipanti a questo evento",
    meetingPointAssignments: "Assegnazioni punti di ritrovo:",
    participantAlreadyJoined: "partecipanti già iscritti.",
    noParticipantsSignIn: "Nessun partecipante ancora.",
    promoExpired: "Promozione scaduta",
  },

  en: {
    // Navigation
    home: "Home",
    myEvents: "My Events",
    organize: "Organize",
    merch: "Merch",
    profile: "Profile",

    // Header
    search: "Search",
    toggleTheme: "Toggle theme",
    signIn: "Sign In",

    // Index / Home
    searchEvents: "Search events...",
    date: "Date",
    allPrices: "All prices",
    free: "Free",
    paid: "Paid",
    clearAll: "Clear all",
    searchResults: "Search Results",
    upcomingEvents: "Upcoming Events",
    noEventsFound: "No events found",
    clearFilters: "Clear filters",
    featuredEvent: "Featured Event",
    discover: "Discover",
    today: "Today!",
    tomorrow: "Tomorrow",
    past: "Past",
    inDays: "In {days} days",
    spotsLeft: "{count} spot{count, plural, one {} other {s}} left",

    // Event Card
    draft: "Draft",
    open: "Open",
    full: "Full",
    closed: "Closed",
    cancelled: "Cancelled",

    // Event Detail
    description: "Description",
    gallery: "Gallery",
    equipment: "Equipment",
    mandatoryEquipment: "Mandatory Equipment",
    recommendedEquipment: "Recommended Equipment",
    safetyNotice: "Safety notice:",
    safetyNoticeText: "Participants who arrive without the required mandatory equipment may not be allowed to join the activity for safety reasons.",
    meetingPoints: "Meeting Points",
    participants: "Participants",
    joined: "Joined",
    noParticipantsYet: "No participants yet",
    signInAndJoin: "Sign in and join to see who's going.",
    joinToSee: "Join to see who's going.",
    beFirstToJoin: "Be the first to join.",
    signInAndBe: "Sign in and be the first to join.",
    organizer: "Organizer",
    viewProfile: "View Profile",
    contactInfoNotAvailable: "Contact info not available",
    signInToContact: "Sign in to contact the organizer",
    directions: "Directions",
    addToCalendar: "Add to Calendar",
    distance: "Distance",
    elevation: "Elevation",
    duration: "Duration",
    spots: "Spots",
    price: "Price",
    from: "From",
    yourPrice: "Your price",
    deposit: "Deposit",
    total: "total",
    payOnLocation: "pay on location",
    eventClosed: "Event Closed",
    signInToJoin: "Sign in to Join",
    approvalPending: "Approval Pending",
    onWaitlist: "On Waitlist",
    payNow: "Pay Now",
    registered: "Registered ✔",
    joinWaitlist: "Join Waitlist",
    viewRequirements: "View Requirements",
    joinEvent: "Join Event",
    requestManualApproval: "Request manual approval",
    cancelRegistration: "Cancel Registration",
    cancelling: "Cancelling...",

    // Registration Dialog
    registerFor: "Register for {title}",
    completeRegistration: "Complete your registration by selecting the required options.",
    meetingPoint: "Meeting Point",
    sportLevel: "Sport Level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    orEnterCustomLevel: "Or enter custom level (e.g. 3.5 for padel)",
    helpsOrganizers: "Helps organizers balance teams and plan activities",
    choosePricingOption: "Choose your pricing option",
    discountCode: "Discount Code",
    optional: "optional",
    membershipRequired: "Membership Required",
    membershipRenewalRequired: "Membership Renewal Required",
    orderSummary: "Order Summary",
    event: "Event",
    discountApplied: "Discount applied",
    remainingPayLater: "Remaining (pay later)",
    paymentOnLocation: "Payment on location — no charge during registration.",
    membershipFee: "Membership fee",
    totalDueToday: "Total due today",
    membershipIncludedInCheckout: "Membership fee is included in this Stripe checkout.",
    fullPaymentViaStripe: "Full payment will be charged online via Stripe.",
    depositViaStripe: "Deposit will be charged online via Stripe.",
    confirmRegistration: "Confirm Registration",
    renewMembershipAndRegister: "Renew Membership & Register",
    payMembershipAndRegister: "Pay Membership & Register",
    submitRequest: "Submit Request",
    redirectingToPayment: "Redirecting to payment...",
    registering: "Registering...",
    submitting: "Submitting...",
    equipmentConfirmation: "I have the required mandatory equipment",

    // Membership Info
    membershipCardTitle: "Tessera Associativa Scampagnate",
    membershipExpiredText: "Your membership has expired. Renewal is required to continue participating in activities.",
    membershipKeepId: "Your membership number will be retained.",
    membershipNewText: "An annual membership card is required to participate in activities organized by Gruppo Scampagnate.",
    membershipAfterPayment: "After payment you will receive your personal membership number. The physical card will be delivered at your first event.",
    membershipFeePerYear: "The membership fee is €10/year and covers the entire calendar year {year}.",

    // Payment Info
    fullPaymentOnline: "Full Payment Online",
    paymentOnLocationTitle: "Payment on Location",
    splitPayment: "Split Payment",
    totalPrice: "Total price",
    depositOnlineStripe: "Deposit (online via Stripe)",
    remainingBalance: "Remaining balance",
    remainingBalanceText: "Remaining balance can be paid before the event or on location.",
    fullAmountStripe: "Full amount will be charged online via Stripe during registration.",
    paymentCollectedOnLocation: "Payment will be collected on location at the event.",
    depositRefundPolicy: "Deposit refund is subject to this policy.",
    cancellationPolicy: "Cancellation Policy",

    // Access Warning
    accessRequirements: "Access Requirements",
    requirementsNotMet: "Requirements not met:",
    accessWarningDefault: "This event has participation requirements.",
    accessWarningText: "You can still request manual approval from the organizer or contact them directly for more information.",
    contactOrganizer: "Contact organizer",
    requestManualApprovalBtn: "Request manual approval",
    close: "Close",

    // Private/Hidden
    private: "Private",
    hidden: "Hidden",

    // My Events
    upcoming: "Upcoming",
    saved: "Saved",
    noUpcomingEvents: "No upcoming events.",
    browseEvents: "Browse Events",
    noSavedEvents: "No saved events yet.",
    tapBookmark: "Tap the bookmark icon on any event to save it for later.",
    noPastEvents: "No past events.",
    share: "Share",
    calendar: "Calendar",
    cancel: "Cancel",
    cancelRegistrationTitle: "Cancel Registration?",
    cancelRegistrationText: "Are you sure you want to cancel your registration for {title}?",
    keep: "Keep",

    // Profile
    signInToViewProfile: "Sign in to view your profile.",
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone",
    bio: "Bio",
    categoryPreferences: "Category Preferences",
    preferences: "Preferences",
    membership: "Membership",
    status: "Status",
    activeMember: "Active Member",
    expiredMember: "Expired",
    inactiveMember: "Inactive Member",
    foundingMember: "Founding Member",
    memberId: "Member ID",
    memberSince: "Member Since",
    validUntil: "Valid Until",
    membershipExpiredRenew: "Your membership has expired. Renew to continue joining events.",
    joinFirstEvent: "Join your first event to activate your annual membership and receive your unique ID!",
    badges: "Badges",
    officialMember: "Official community member",
    nextBadge: "Next badge",
    joinEventsToEarnBadges: "Join events to earn badges!",
    pastEvents: "Past Events",
    noPastEventsJoinFirst: "No past events yet. Join your first event!",
    helpAndInfo: "Help & Information",
    trekkingDifficultyGuide: "Trekking Difficulty Guide",
    signOut: "Sign Out",
    profileUpdated: "Profile updated!",
    profilePhotoUpdated: "Profile photo updated!",
    points: "points",
    copied: "Copied!",
    memberIdCopied: "Member ID #{id} copied to clipboard.",

    // Auth
    welcomeBack: "Welcome Back!",
    joinUs: "Join Us",
    signInToAccount: "Sign in to your account",
    createAccount: "Create your Scampagnate account",
    continueWithGoogle: "Continue with Google",
    continueWithApple: "Continue with Apple",
    orContinueWithEmail: "Or continue with email",
    email: "Email",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    signingIn: "Signing In...",
    signingUp: "Signing Up...",
    signUp: "Sign Up",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    acceptPrivacy: "I accept the",
    privacyPolicy: "Privacy Policy",
    and: "and",
    termsOfService: "Terms of Service",
    viewDifficultyGuide: "View Trekking Difficulty Guide",
    learnCriteria: "Learn our 5-level standardized criteria for joining events safely.",
    resetPassword: "Reset Password",
    resetPasswordDesc: "Enter your email and we'll send you a reset link",
    sendResetLink: "Send Reset Link",
    sending: "Sending...",
    backToSignIn: "Back to Sign In",
    passwordStrengthWeak: "Weak",
    passwordStrengthFair: "Fair",
    passwordStrengthGood: "Good",
    passwordStrengthStrong: "Strong",
    atLeast8Chars: "At least 8 characters",
    uppercaseLetter: "Uppercase letter",
    lowercaseLetter: "Lowercase letter",
    number: "Number",
    specialCharacter: "Special character",
    accountCreated: "Welcome! Your account has been created successfully.",
    registrationComplete: "Registration complete! Check your email to confirm your account.",
    errorAcceptPrivacy: "You must accept the privacy policy",
    emailSent: "Email sent!",
    checkEmailReset: "Check your email to reset your password.",
    enterYourEmail: "Enter your email",
    pleaseEnterEmail: "Please enter your email address.",

    // Merch
    merchandise: "Merchandise",
    merchDescription: "Official Scampagnate branded products. Contact us via WhatsApp to purchase.",
    whatsapp: "WhatsApp",
    merchOrderInfo: "All orders are managed manually via WhatsApp.",
    merchDeliveryInfo: "Delivery details and payment will be arranged directly with the team.",

    // Notifications
    notifications: "Notifications",
    markAll: "Mark all",
    noNotifications: "No notifications",
    notificationsWillAppear: "Notifications will appear here",
    pushOn: "Push ON",
    push: "Push",
    openNavigation: "Open Navigation",

    // Not Found
    pageNotFound: "Oops! Page not found",
    returnToHome: "Return to Home",

    // Proposal
    proposeActivity: "Propose Activity",
    haveIdea: "Have an idea for a new activity?",
    proposeIt: "Propose it to the community!",
    thankYouProposal: "Thank you for your proposal!",
    proposalReview: "The Scampagnate team will evaluate it and may contact you to organize the activity.",
    proposeActivityTitle: "Propose an Activity",
    proposeActivityDesc: "Suggest a new activity to the community. The team will evaluate your proposal.",
    yourName: "Your name",
    activityTitle: "Activity title",
    whatIsIt: "What is it about?",
    location: "Location",
    locationPlaceholder: "City, specific place or Google Maps link",
    suggestedDate: "Suggested date",
    time: "Time",
    maxParticipants: "Max participants",
    submitProposal: "Submit Proposal",

    // Report Issue
    reportIssue: "Report an Issue",
    title: "Title",
    briefSummary: "Brief summary of the issue",
    descriptionLabel: "Description",
    describeIssue: "Describe the issue in detail...",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    submitReport: "Submit Report",
    thankYouReporting: "Thank you for reporting!",
    reportReceived: "We've received your report and will look into it soon.",
    pleaseFillFields: "Please fill in all fields",
    inputTooLong: "Input too long",
    titleMax200: "Title max 200 chars, description max 2000 chars.",

    // Toasts & messages
    error: "Error",
    requestSent: "Request sent",
    manualApprovalSent: "Your manual approval request has been sent to the organizer.",
    addedToWaitlist: "Added to waitlist",
    waitlistNotify: "You'll be notified when a spot opens for {title}",
    registrationConfirmed: "Registration confirmed",
    registeredFor: "You've registered for {title}",
    registrationCancelled: "Registration cancelled",
    registrationCancelledDesc: "Your registration has been cancelled.",
    removedFromSaved: "Removed from saved",
    savedToWishlist: "Saved to wishlist",
    removedFromSavedEvents: "Removed from saved events",
    paymentCompleted: "Payment completed",
    discountCoveredAmount: "The discount covered the full amount!",
    uploadError: "Upload error",

    statusPaid: "Paid",
    attended: "Attended",
    noShow: "No-show",

    // Misc
    everyoneJoining: "Everyone joining this event",
    meetingPointAssignments: "Meeting point assignments:",
    participantAlreadyJoined: "participants already joined.",
    noParticipantsSignIn: "No participants yet.",
    promoExpired: "Promo expired",
  },
} as const;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof TranslationKeys, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved === "en" || saved === "it") ? saved : "it";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  }, []);

  const t = useCallback(
    (key: keyof TranslationKeys, params?: Record<string, string | number>): string => {
      let text = (translations[language] as any)[key] || (translations.it as any)[key] || key;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          text = text.replace(`{${k}}`, String(v));
        });
      }
      return text;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
